<a href="https://colab.research.google.com/github/danielbrodev/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [6]:
import numpy as np


arr = np.array([1,2,3,4,5])
print('numpy_array:',arr)

arr.shape

numpy_array: [1 2 3 4 5]


(5,)

In [7]:
arr2 = np.array([[1,2,3,4,5],[4,6,7,8,6]])
print('numpy_array2:',arr2)

arr2.shape

numpy_array2: [[1 2 3 4 5]
 [4 6 7 8 6]]


(2, 5)

In [8]:
# dtype()
a = np.array([1,2,3,4])
print(a.dtype)

int64


In [9]:
# reshape()
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print('shaped_array:',b)


shaped_array: [[1 2 3]
 [4 5 6]]


In [12]:
#astpye()
a = np.array([1,2,3])
b = a.astype(float)
print('float:',b)

float: [1. 2. 3.]


In [13]:
import numpy as np

# np.zeros() np.ones() => dummy data
zer = np.zeros((2, 3))
on = np.ones((2, 3))

print('zeros:', zer)
print('ones:', on)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# ndim
a = np.array([[1,2],[3,4]])

print('ndim:',a.ndim)

ndim: 2


In [16]:
# arrange()
a = np.arange(1,6)
print("arange:",a)

arange: [1 2 3 4 5]


In [20]:
# sum(), mean(), max(), min()
a = np.array([1,2,3,4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.0
max: 4
min: 0


In [21]:
# flatten()

a = np.array([[1,2],[3,4]])
print("flatten:",a.flatten())

flatten: [1 2 3 4]


In [22]:
# T (Transpose)

a = np.array([[1,2],[3,4]])
print("transpose:",a.T)


transpose: [[1 3]
 [2 4]]


In [23]:
# dot() @

a = np.array([[1,2],[3,4]])
b = np.array([[2,0],[1,2]])
print("dot/multiplication:",a.dot(b))


dot/multiplication: [[ 4  4]
 [10  8]]


In [31]:
import numpy as np

# random.rand()
a = np.random.rand(2,3) # => 0.0 and 1.0 / 0.0 included / 1.0 excluded
print("random rand:", a)



random rand: [[0.25815604 0.75582038 0.50218081]
 [0.63479459 0.64340756 0.81258721]]
